version: '3.9'


services:
    app:
        build:
            context: .
            target: prod
        image: linkedout/app
        hostname: linkedout-app
        restart: unless-stopped
        volumes:
            - ./apache2/sites-enabled:/etc/apache2/sites-enabled
        networks:
            - internal
            - external
        depends_on:
            -   db
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
            JWT_SECRET: ${JWT_SECRET}
            APP_ENV: production

    db:
        image: mysql:8.0
        hostname: ${MYSQL_HOST}
        restart: unless-stopped
        volumes:
            - linkedout-mysql:/var/lib/mysql
        networks:
            - internal
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}


volumes:
    linkedout-mysql:
        external: true
        name: linkedout-mysql


networks:
    internal:
        external: false
        name: linkedout-internal
    external:
        external: true
        name: linkedout
