version: '3.9'


services:
    app:
        build:
            context: .
            target: base
        ports:
            - "80:80"
        volumes:
            -   ./www:/var/www/html

    db:
        ports:
            - "3306:3306"


volumes:
    linkedout-mysql:
        external: false
        name: linkedout-mysql


networks:
    internal:
        external: false
        name: linkedout-internal
    external:
        external: false
        name: linkedout
